### ISSUE TITLE
Не оптимальный алгоритм подсчета возраста

### ISSUE THREAD

**Issue by Vyacheslav-GrebenyukNURE** [NUREKN16-JAVA/kostiantyn.yavorovenko#1]
Согласно нашей дискуссии: https://docs.google.com/document/d/1_LAaxoTMbMoA8vSYDqSWbal7rE2U3KsgMVC6FkAY6Tk/edit?disco=AAAACQ6N3u8
Алгоритм подсчета возраста требует оптимизации.

**Comment by bacardl** [comment]
![image](https://user-images.githubusercontent.com/34916854/49226830-b346ca00-f3f8-11e8-880f-196655956715.png)
[https://github.com/NUREKN16-JAVA/kostiantyn.yavorovenko/commit/45f56f970e630ed423de967673ee8ada57bd2edb](url)
